export interface ReviewItem {
  id: string;
  outputName: string;
  claimId: string;
  generatedContent: string;
  originalSourceSnippet: string;
  sourceDoc: string;
  pageNumber: number;
  flagReason: string;
  authorship: {
    machineAuthored: string;
    operatorModified?: string;
    reviewerApproved?: string;
  };
  status: 'PENDING' | 'APPROVED' | 'EDITED' | 'REJECTED';
  timeline: Array<{
    time: string;
    action: string;
    by: string;
  }>;
}

export const PENDING_REVIEWS: ReviewItem[] = [
  {
    id: 'REV-2026-01',
    outputName: 'Executive Summary',
    claimId: 'CLM-001',
    generatedContent: 'Revenue reached all-time record levels across every enterprise product line in FY2026.',
    originalSourceSnippet: 'Page 4, Paragraph 2: "Total consolidated revenue reached $4.2B, representing an 18% YoY increase compared with the previous fiscal period."',
    sourceDoc: 'Annual_Report_2026.pdf',
    pageNumber: 4,
    flagReason: 'Fidelity Gate flagged "all-time record levels" as unverified claim embellishment.',
    authorship: {
      machineAuthored: 'Agent Alpha-Exec (10:42 UTC)',
    },
    status: 'PENDING',
    timeline: [
      { time: '10:42', action: 'Generated by Agent Alpha-Exec', by: 'System Engine' },
      { time: '10:44', action: 'Fidelity Gate Flagged Review Required', by: 'Gate 1 Engine' }
    ]
  },
  {
    id: 'REV-2026-02',
    outputName: 'Strategic Advisory',
    claimId: 'CLM-003',
    generatedContent: 'The organization will dominate two key European jurisdictions before year-end.',
    originalSourceSnippet: 'Page 8, Section 4.2: "Geographic expansion initiatives target operational launches in Germany and France before year-end."',
    sourceDoc: 'Annual_Report_2026.pdf',
    pageNumber: 8,
    flagReason: 'Tone mismatch & potential premature external market announcement.',
    authorship: {
      machineAuthored: 'Agent Epsilon-Advisory (10:45 UTC)',
      operatorModified: 'Operator J. Vance (10:46 UTC)'
    },
    status: 'PENDING',
    timeline: [
      { time: '10:45', action: 'Generated by Agent Epsilon-Advisory', by: 'System Engine' },
      { time: '10:46', action: 'Operator reworded tone', by: 'Operator J. Vance' }
    ]
  }
];
